---
title: "R Notebook"
output: html_notebook
---

Data Set Link: https://www.propublica.org/datastore/dataset/compas-recidivism-risk-score-data-and-analysis
GitHub Link: https://github.com/propublica/compas-analysis/

```{r}
library(dplyr)
library(ggplot2)

data = read.csv('/Users/zebbogue/Documents/GitHub/325-Group-Project/Group Project/compas-scores-raw.csv')
```

```{r}
dim(data) #60843 rows and 28 columns
str(data) 
summary(data) #gives column names, and classes (all characters)

head(data, 10)
```

Renaming columns to better format
```{r}
data = data %>% rename(person_id = Person_ID,
                assessment_id = AssessmentID,
                case_id = Case_ID,
                agency_text = Agency_Text,
                last_name = LastName,
                first_name = FirstName,
                middle_name = MiddleName,
                sex = Sex_Code_Text,
                ethnicity = Ethnic_Code_Text,
                dob = DateOfBirth,
                scale_set_id = ScaleSet_ID,
                scale_set = ScaleSet,
                assessment_reason = AssessmentReason,
                language = Language,
                legal_status = LegalStatus,
                custody_status = CustodyStatus,
                marital_status = MaritalStatus,
                screening_date = Screening_Date,
                rec_supervision_level = RecSupervisionLevel,
                rec_supervision_level_text = RecSupervisionLevelText,
                scale_id = Scale_ID,
                display_text = DisplayText,
                raw_score = RawScore,
                decile_score = DecileScore,
                score_text = ScoreText,
                assessment_type = AssessmentType,
                is_completed = IsCompleted,
                is_deleted = IsDeleted)

```


```{r}
unique(data$ethnicity) 
#ethnicities split into "Caucasian", "African-American", "Hispanic", "Other", "Asian", "African-Am", "Native American", "Oriental", "Arabic" 

data$ethnicity = gsub('African-Am', 'African-American', data$ethnicity) #African-Am into African-american
data$ethnicity = gsub('African-Americanerican', 'African-American', data$ethnicity) #African-Americanerican into African-American
```

```{r}
data %>% group_by(last_name, first_name) %>%
  filter(display_text == 'Risk of Recidivism') %>%
  summarize(decile_score)
```

